import Background from "@/assets/images/auth-background.png";
import { BaseButton, BaseText, ScreenContainer } from "@/shared/ui";
import { Colors } from "@/shared/constants";
import { useAppDispatch } from "@/store/hooks";
import { setCredentials, useVerify2FAMutation } from "@/store/store";
import { showToast } from "@/shared/utils";
import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import React, { useEffect, useMemo, useRef, useState } from "react";
import {
    Image,
    KeyboardAvoidingView,
    Platform,
    StyleSheet,
    TextInput,
    TouchableOpacity,
    View,
} from "react-native";

export default function TwoFactorScreen() {
  const dispatch = useAppDispatch();
  const { challengeId } = useLocalSearchParams<{
    challengeId: string;
  }>();

  const [verify2FA, { isLoading: isVerifying }] = useVerify2FAMutation();
  const [digits, setDigits] = useState(["", "", "", "", "", ""]);
  const [error, setError] = useState("");

  const ref1 = useRef<TextInput>(null);
  const ref2 = useRef<TextInput>(null);
  const ref3 = useRef<TextInput>(null);
  const ref4 = useRef<TextInput>(null);
  const ref5 = useRef<TextInput>(null);
  const ref6 = useRef<TextInput>(null);

  const inputRefs = useMemo(() => [ref1, ref2, ref3, ref4, ref5, ref6], []);

  const handleChangeText = (text: string, index: number) => {
    const cleaned = text.replace(/[^0-9]/g, "");
    const newDigits = [...digits];
    newDigits[index] = cleaned;
    setDigits(newDigits);

    if (error) setError("");

    // Move to next input if filled
    if (cleaned && index < 5) {
      inputRefs[index + 1].current?.focus();
    }
  };

  const handleKeyPress = (e: any, index: number) => {
    if (e.nativeEvent.key === "Backspace" && !digits[index] && index > 0) {
      inputRefs[index - 1].current?.focus();
    }
  };

  const handleContinue = async () => {
    const code = digits.join("");
    if (code.length < 6) {
      setError("Please enter the complete 6-digit code");
      return;
    }
    setError("");

    try {
      const res = await verify2FA({
        challengeId,
        code,
      }).unwrap();

      if (res && "accessToken" in res) {
        showToast("success", "Signed in successfully.");
        dispatch(
          setCredentials({
            user: res.user,
            accessToken: res.accessToken,
            refreshToken: res.refreshToken,
          }),
        );
        router.replace("/(tabs)/home");
      }
    } catch (err: any) {
      setError(err?.data?.message || "Verification failed");
      showToast("error", err?.data?.message || "Verification failed");
    }
  };

  const navigateToRecovery = () => {
    router.push({
      pathname: "/(auth)/recovery",
      params: { challengeId },
    });
  };

  // Auto-focus first input box on mount
  useEffect(() => {
    const focusTimeout = setTimeout(() => {
      inputRefs[0].current?.focus();
    }, 150);

    return () => clearTimeout(focusTimeout);
  }, [inputRefs]);

  return (
    <ScreenContainer
      scrollable={false}
      withPadding={true}
      avoidKeyboard={false}
      style={styles.container}
    >
      <Image
        source={Background}
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: "120%",
        }}
      />
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        style={{ flex: 1 }}
        keyboardVerticalOffset={Platform.OS === "ios" ? 20 : 0}
      >
        <View style={{ flex: 1 }}>
          {/* Back Button Header */}
          <TouchableOpacity
            onPress={() => router.back()}
            style={styles.backButton}
          >
            <Ionicons name="arrow-back" size={24} color={Colors.white} />
            <BaseText variant="bold" style={styles.backButtonText}>
              Sign In
            </BaseText>
          </TouchableOpacity>

          <View style={styles.content}>
            <BaseText variant="bold" style={styles.title}>
              Two-Factor Auth
            </BaseText>
            <BaseText style={styles.subtitle}>
              Please enter the 6-digit code generated by your authenticator app.
            </BaseText>

            {/* OTP Digit Blocks */}
            <View style={styles.otpInputContainer}>
              {digits.map((digit, index) => (
                <View key={index} style={styles.otpInputBox}>
                  <TextInput
                    ref={inputRefs[index]}
                    style={styles.otpInput}
                    keyboardType="numeric"
                    maxLength={1}
                    value={digit}
                    onChangeText={(text) => handleChangeText(text, index)}
                    onKeyPress={(e) => handleKeyPress(e, index)}
                    placeholderTextColor="#4E586E"
                    placeholder="-"
                  />
                </View>
              ))}
            </View>

            {error ? <BaseText style={styles.errorText}>{error}</BaseText> : null}

            {/* Use Recovery Code */}
            <View style={styles.recoveryContainer}>
              <TouchableOpacity onPress={navigateToRecovery}>
                <BaseText style={styles.recoveryLinkText}>
                  Lost access? Use a recovery code
                </BaseText>
              </TouchableOpacity>
            </View>
          </View>

          <BaseButton
            title="Verify & Sign In"
            onPress={handleContinue}
            isLoading={isVerifying}
            style={styles.submitButton}
          />
        </View>
      </KeyboardAvoidingView>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.secondary,
    paddingTop: 10,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  backButtonText: {
    color: Colors.white,
    fontSize: 16,
    marginLeft: 8,
  },
  content: {
    flex: 1,
  },
  title: {
    fontSize: 32,
    color: Colors.white,
    marginBottom: 10,
    marginTop: 10,
  },
  subtitle: {
    fontSize: 14,
    color: "#A7AFB7",
    lineHeight: 20,
    marginBottom: 40,
  },
  otpInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  otpInputBox: {
    width: 50,
    height: 50,
    backgroundColor: "#161C22",
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#252E38",
  },
  otpInput: {
    fontSize: 24,
    fontWeight: "bold",
    color: Colors.white,
    textAlign: "center",
    width: "100%",
    height: "100%",
  },
  errorText: {
    color: Colors.error,
    fontSize: 12,
    textAlign: "center",
    marginBottom: 10,
  },
  recoveryContainer: {
    alignItems: "center",
    marginTop: 20,
  },
  recoveryLinkText: {
    fontSize: 14,
    color: Colors.primary,
  },
  submitButton: {
    height: 56,
    borderRadius: 15,
    marginBottom: 30,
  },
});
