name: Publish preview update

on:
  push:
    branches: ["*"]

jobs:
  publish_preview_update:
    name: Publish preview update
    type: run
    steps:
      - uses: eas/checkout
      - uses: eas/setup-node
      - name: Publish update to preview channel
        run: npx eas-cli update --channel preview --non-interactive

